### ISSUE TITLE
Remove maker from whitelist when deauthorize

### ISSUE THREAD

**Issue by akash2504** [ethfinex/nectar#2]
/// @dev deauthoriseMaker
  /// @param maker - Source to remove from authorised contributors
  function deauthoriseMaker(address maker) onlyOwner {
      isAuthorisedMaker[maker] = false;

      **// Remove maker from the whitelist
      address[] memory makers = new address[](1);
      makers[0] = maker;
      deregister(makers);**
  }

**Comment by ipatka** [comment]
A mapping is kind of like a hash table, not an array and there is no length. When it is initialized every possible key already exists and is mapped to the default. In this case, false. The key data is not stored. By setting it back to false it is the same as deregistering an address. See the documentation here: http://solidity.readthedocs.io/en/develop/types.html#mappings

**Comment by plutoegg** [comment]
Thanks @akash2504 the intention here is that even though they are being deauthorised as a source for contributing to the contract, they may stay on the whitelist, and so removing them from that will need to be a separate action.

This is different from when they are added as an authority, since they are required to be registered on the whitelist also in order to act as an authority.
